# How to install numpy 

# How to import numpy 

In [11]:
# How to import the Numpy library

import numpy as np 

# where np is the alias other wise numpy should be used every where

In [17]:
# How to create numpy array

import numpy as np # This is optional because in the previous cell itself I have imported where jupyter notebook is interrelated

onedarray=np.array([1,2,3,4])

print(f"One dimensional array {onedarray}")

twodarray=np.array([[1,2,3,4],[5,6,7,8]])

print(f"Two dimensional array\n{twodarray}")

threedarray=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])

print(f"Three dimensional array \n{threedarray}")

One dimensional array [1 2 3 4]
Two dimensional array
[[1 2 3 4]
 [5 6 7 8]]
Three dimensional array 
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [18]:
# To check the Data type of the numpy array

print(type(onedarray))
print(type(twodarray))
print(type(threedarray))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [19]:
# To check the Number of element in the numpy array 

print(onedarray.size)
print(twodarray.size)
print(threedarray.size)

4
8
12


In [20]:
# To check the element data type that is used in numpy array

print(onedarray.dtype)
print(twodarray.dtype)
print(threedarray.dtype)

int32
int32
int32


In [21]:
# lets check the dtype of the float and string

a=np.array(["hello","hi"])
b=np.array([1,2.2,3])

print(a.dtype)
print(b.dtype)

<U5
float64


In [23]:
# To get the shape of the np array like rows column matrix in each dimension just check the chatgpt once for more clear understand of size it is easier

print(onedarray.shape)
print(twodarray.shape)
print(threedarray.shape)

(4,)
(2, 4)
(2, 2, 3)


In [26]:
# To get the transpose of the numpy array transpose is nothing but n*m -> m*n

import numpy as np 

notrans=np.array([[1,2,3],[4,5,6]])

trans=notrans.T; # or notrans.transpose() also works 

print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
# To get the dimension of the array

print(notrans.ndim)

2
