In [2]:
# Creation of 1,2,3 dimesional array using np.empty()

# Sytax -> np.empty(col,dtype) -> 1d
# Sytax -> np.empty((rows,cols),dtype) -> 2d
# Sytax -> np.empty((matrix,rows,col),dtype) -> 3d
import numpy as np

a=np.empty(6,int)
b=np.empty((2,3),int)
c=np.empty((2,2,3),int)# 2 matrix with 2*3 rows and col you can also specify float double and etc

print(a)
print(b)
print(c) # np.empty which will put random data to the specify shape

[         0          0 2071888432        522 2071888112        522]
[[2066713688        522          0]
 [         0          0          0]]
[[[     0      1      1]
  [     0      0      0]]

 [[     0      0      0]
  [     0      0 524288]]]


In [4]:
# Creation of 1,2,3 dimensional array using np.ones()

# Syntax -> np.ones(col,dtype) -> 1d
# Syntax -> np.ones((row,col),dtype) -> 2d
# Syntax -> np.ones((number of matrix,row,col),dtype) -> 3d

a=np.ones(6,int) 
b=np.ones((2,3),float)
c=np.ones((2,3,3),float) 

print(a)
print(b)
print(c)

[1 1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [5]:
# Creation of 1,2,3 dimensional array using np.ones()

# Syntax -> np.zeros(col,dtype) -> 1d
# Syntax -> np.zeros((row,col),dtype) -> 2d
# Syntax -> np.zeros((number of matrix,row,col),dtype) -> 3d

a=np.zeros(6,int) 
b=np.zeros((2,3),float)
c=np.zeros((2,3,3),float) 

print(a)
print(b)
print(c)

[0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [6]:
# numpy array accessing is same as that of array 

print(a[0])
print(b[0][1])
print(c[0][1][2])

0
0.0
0.0
