### Arange function in numpy 

In [4]:
# Sytax- np.arange(start,end,step)

import numpy as np

# it just assign the a with the numpy array starting with 1 and upto end-1 
a=np.arange(1,10)

print(a)

[1 2 3 4 5 6 7 8 9]


In [2]:
# it also same but it step by 1 for example is 1,10 is start and end 1 is assigned 2 is left and 3 is assigned 1+2=3 3+step=5
b=np.arange(1,10,2)

print(b)

[1 3 5 7 9]


### Reshape function in numpy

In [6]:
# Sytax- array.reshape((rows,col))

import numpy as np 

# This is the 1d array where it is consisting of 9 elements
a=np.arange(1,10)

# To reshape the array there should rows*col number of element in the reshaping array means in below a numpy array there should 3*3=9 element
a=a.reshape((3,3))

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Sytax- array.reshape((rows,col))

import numpy as np 

# This is the 1d array where it is consisting of 9 elements
a=np.arange(1,11)

# To reshape the array there should rows*col number of element in the reshaping array means in below a numpy array there should 3*3=9 element but there is no correct n and m value given
a=a.reshape((3,3))

print(a)

ValueError: cannot reshape array of size 10 into shape (3,3)

### Flatten function in numpy 

In [21]:
import numpy as np 

a=np.arange(1,11)
print(a)

a=a.reshape((5,2))
print(a)

a=a.flatten() # what ever the numpy array is it just flatten it into 1-d array
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
a=a.reshape((5,2))
a=a.ravel()
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### Difference between ravel and flatten
#### Ravel
##### * View or Copy: ravel returns a flattened array. If possible, it returns a view of the original array, meaning changes to the flattened array will affect the original array. If a view is not possible, it returns a copy.
##### * Faster: it does n't required any extra memory it is faster
#### Flatten
##### * Always a Copy: flatten always returns a copy of the original array, so changes to the flattened array do not affect the original array.

In [25]:
# Flatten example

a=np.arange(1,11)
a=a.reshape((2,5))
b=a.flatten()
print('Before changing the b numpy')
print('a')
print(a)
print('b')
print(b)
b[1]=20
print('After changing the b numpy')
print('a')
print(a)
print('b')
print(b)

Before changing the b numpy
a
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
b
[ 1  2  3  4  5  6  7  8  9 10]
After changing the b numpy
a
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
b
[ 1 20  3  4  5  6  7  8  9 10]


##### If you look at the above the b changed but not a 

In [28]:
# ravel example

a=np.arange(1,11)
a=a.reshape((2,5))
b=a.ravel()
print('Before changing the b numpy')
print('a')
print(a)
print('b')
print(b)
b[1]=20
print('After changing the b numpy')
print('a')
print(a)
print('b')
print(b)

Before changing the b numpy
a
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
b
[ 1  2  3  4  5  6  7  8  9 10]
After changing the b numpy
a
[[ 1 20  3  4  5]
 [ 6  7  8  9 10]]
b
[ 1 20  3  4  5  6  7  8  9 10]


##### If you look at the above the b changed also a 