In [2]:
# Addition 
import numpy as np

a=np.arange(1,17)
b=np.arange(5,21)
a=a.reshape((4,4))
b=b.reshape((4,4))

c=a+b
print(c)

[[ 6  8 10 12]
 [14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]


In [4]:
d=np.add(a,b)
print(d)

[[ 6  8 10 12]
 [14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]


In [6]:
#subtraction

e=a-b
print(e)

[[-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [-4 -4 -4 -4]]


In [7]:
f=np.subtract(a,b)
print(f)

[[-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [-4 -4 -4 -4]]


In [8]:
# common multiplication
g=a*b# np.multiply(a,b)
print(g)

[[  5  12  21  32]
 [ 45  60  77  96]
 [117 140 165 192]
 [221 252 285 320]]


In [9]:
# matrix multiplication
h=a@b # np.dot(a,b)
print(h)

[[130 140 150 160]
 [306 332 358 384]
 [482 524 566 608]
 [658 716 774 832]]


In [11]:
#Maximum in Array

i=b.max()
print(i)

20


In [12]:
# Minimum in array

j=b.min()
print(j)

5


In [13]:
# index of largest element

k=b.argmax()
print(k)

15


In [14]:
# Sumattion of all element in the array

sum=np.sum(b)
print(sum)

200


In [17]:
# axis=0->col
# axis=1->row

np.sum(b,axis=1) #->row sum


array([26, 42, 58, 74])

In [18]:
np.sum(b,axis=0) #->col sum

array([44, 48, 52, 56])

In [19]:
np.log(b)

array([[1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872],
       [2.83321334, 2.89037176, 2.94443898, 2.99573227]])

In [20]:
np.mean(b)

12.5

In [21]:
np.sqrt(b)

array([[2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894, 4.47213595]])

In [22]:
np.std(b) # Standard deviation of b

4.6097722286464435