In [4]:
import numpy as np

In [5]:
np.random.random(1) # it provide the array with 1 random number

array([0.65288157])

In [6]:
np.random.random(2) # it provide the array with 2 random number

array([0.64074998, 0.61988736])

In [8]:
np.random.random((2,2)) # it provide the array with 2*2 random number

array([[0.55512601, 0.00722515],
       [0.80973601, 0.51782366]])

In [9]:
np.random.randint(1,10)

4

In [10]:
np.random.randint(1,10,(2,2)) # gives 2*2 matrix with random number from 1 to 10 

array([[3, 2],
       [2, 8]])

In [11]:
np.random.rand(2,2) # only positive things

array([[0.096253  , 0.16024482],
       [0.9059264 , 0.90120138]])

In [13]:
np.random.randn(2,2) # combination of both positive and negative

array([[-1.7667616 ,  0.05084548],
       [ 0.20836637, -0.09917384]])

In [15]:
a=np.array([1,2,3,4])

np.random.choice(a) # it choice from the provided array

4