In [2]:
# To check the type of numpy

import numpy as np 

values=np.array([1,2,3]);

print(values);

print(type(values));

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# Creation of 1d array using numpy library

# Array can also be created using tuples 

import numpy as np 

values=np.array((1,2,3));

print(values);
print(type(values));

[1 2 3]
<class 'numpy.ndarray'>


In [1]:
# Creation of 0d array using numpy library

# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

import numpy as np 

values=np.array(1);

print(values)

1


In [2]:
# Creation of 1d array using numpy library

# 1-d array consisting of 0-d array as the element in it

import numpy as np

values=np.array([1,2,3,4])

print(values)

[1 2 3 4]


In [5]:
# Creation of 2d array using numpy library

# 2-d array consisting of 1-d array as the element in it 

import numpy as np 

values=np.array([[1,2,3],[4,5,6]])

print(values)

[[1 2 3]
 [4 5 6]]


In [6]:
# Creation of 3d array using numpy library

# 3-d array consisting of 2-d array as the element in it 

import numpy as np

values=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])

print(values)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [7]:
# To check the dimension of the numpy array element numpyarray.ndim is used

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.

# When the array is created, you can define the number of dimensions by using the ndmin argument.

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
