In [13]:
# Usual concatination with no parameter this is similer to axis 0 that is row concatenate

import numpy as np

arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6]])

print(np.concatenate((arr1,arr2)))

[[1 2 3]
 [4 5 6]]


In [12]:
# Concatination with axis as 0 that is row concatenation

import numpy as np

arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6]])

print(np.concatenate((arr1,arr2),axis=0))

[[1 2 3]
 [4 5 6]]


In [11]:
# Concatination with axis as 1 that is column concatenation

import numpy as np 

arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([[3,4,5],[4,5,6]])

print(np.concatenate((arr1,arr2),axis=1))

[[1 2 3 3 4 5]
 [2 3 4 4 5 6]]
